### ISSUE TITLE
N1QL query

### ISSUE THREAD

**Issue by AdamMarkowski** [acaprojects/couchbase-orm#1]
Hi!

Is it possible to execute an N1QL query using this library?

**Comment by stakach** [comment]
Sure is. Full text search is also supported.

```ruby
query = MyModel.bucket.n1ql
query.select('*').from(:default).where('name == "bob"')
query.results.stream do |doc|
    puts doc.inspect
end
```

Same as:

```ruby
query = MyModel.bucket.n1ql(select: '*', from: :default, where: 'name == "bob"')
query.results.stream do |doc|
    puts doc.inspect
end
```

References:

https://github.com/cotag/libcouchbase/blob/master/spec/n1ql_spec.rb
https://github.com/cotag/libcouchbase/blob/master/lib/libcouchbase/n1ql.rb
