### ISSUE TITLE
libcouchbase not building correctly

### ISSUE THREAD

**Issue by slash4** [acaprojects/couchbase-orm#2]
Hi, I experience some problems with libcouchbase which seems to build correctly : 

`gem install libcouchbase
Building native extensions.  This could take a while...
Successfully installed libcouchbase-0.1.0
Parsing documentation for libcouchbase-0.1.0
Installing ri documentation for libcouchbase-0.1.0
Done installing documentation for libcouchbase after 17 seconds
1 gem installed`

but when I try to start my rails app : 

`rails c
/Users/alexcentar/.rvm/gems/ruby-2.2.6/gems/ffi-1.9.17/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library '/Users/alexcentar/.rvm/gems/ruby-2.2.6/gems/libcouchbase-0.1.0/ext/libcouchbase/build/lib/libcouchbase.dylib': dlopen(/Users/alexcentar/.rvm/gems/ruby-2.2.6/gems/libcouchbase-0.1.0/ext/libcouchbase/build/lib/libcouchbase.dylib, 5): image not found (LoadError)`

Indeed, no file can be found in the build folder. Any Idea why ?

**Comment by slash4** [comment]
Plus, I wrote to you @stakach on LinkedIn, I would be very glad to chat on slack or IRC about these two projects, couchbase-ruby-model and couchbase-orm, since I just can't make them work. couchbase-ruby-model seems abandonned and not compatible with newer ruby/couchbase versions. Yours seems great, but Rails5 bound, I tried to downgrade your gemspec to Rails4, but still no luck... I wonder if I must persist in my project of using couchbase on ruby. 2 days spent already with absolutely no results.... :(

**Comment by stakach** [comment]
There is an issue with the build returning true even if it fails.
If you run the install like this you'll see the dependency that you are missing:

`gem install libcouchbase --verbose`

**Comment by slash4** [comment]
That's OK ! Very, very good job. Thanks :)

**Comment by stakach** [comment]
Let me know if you have any luck with rails 4 - happy to update the gem to support it. Could change the gemspec to something like

```ruby
gem.add_runtime_dependency     'activemodel',  '>= 4.0', '< 6.0'
```

Which would support both versions :)
